# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
             vb.customize ["modifyvm", :id, "--memory", "1024"]
          end

            box.vm.provision "shell", inline: <<-SHELL
              setenforce 0
              mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
      	      yum install -y rpm-build yum-utils gcc
              yumdownloader --source httpd
	      useradd mockbuild
              rpm -i *.src.rpm
              sed -i 's/disable-imagemap/enable-imagemap/g' /root/rpmbuild/SPECS/httpd.spec
              yum-builddep /root/rpmbuild/SPECS/httpd.spec -y
              rpmbuild -ba /root/rpmbuild/SPECS/*.spec
	      yum install createrepo -y
	      mkdir -p /repos/my-apache/x86_64
  	    cp /root/rpmbuild/RPMS/x86_64/httpd*.rpm /repos/my-apache/
	      createrepo /repos/my-apache/x86_64
	      cp /vagrant/my-apache.repo /etc/yum.repos.d/my-apache.repo
	      yum install httpd --disablerepo="*" --enablerepo="my-apache"
  	  SHELL
      end
  end
end
