# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :log => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
  },
  :web => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.102',
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
                  vb.customize ["modifyvm", :id, "--memory", "1024"]
          end
 	  box.vm.provision "shell", inline: <<-SHELL
              setenforce 0
              mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	      yum install epel-release -y
  	  SHELL

      end
      config.vm.define :web do |web|
          web.vm.provision "shell", inline: <<-SHELL
	      yum install java -y
              rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
              yum install -y https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.rpm 
	  SHELL
      end
      config.vm.define :web do |web|
          web.vm.provision "shell", inline: <<-SHELL
	      yum install nginx -y
	  SHELL
      end
  end
end
