# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :log => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
  },
  :web => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.102',
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
                  vb.customize ["modifyvm", :id, "--memory", "1024"]
          end
 	  box.vm.provision "shell", inline: <<-SHELL
              setenforce 0
              mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
        yum install epel-release -y
        cp /vagrant/elasticsearch.repo /etc/yum.repos.d/elasticsearch.repo
        rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
        if [ "$HOSTNAME" = web ]
        then yum install nginx -y
        yum install filebeat -y
        fi
	      if [ "$HOSTNAME" = log ]
	      then
	      yum install java -y
        
        yum install elasticsearch -y
        sed -i 's/1g/500m/g' /etc/elasticsearch/jvm.options
        sed -i 's/^#bootstrap.memory_lock/bootstrap.memory_lock/g' /etc/elasticsearch/elasticsearch.yml
	      sed -i 's/^#network.host.*/network.host: 192.168.11.101/g' /etc/elasticsearch/elasticsearch.yml
	      sed -i 's/^#http.port/http.port/g' /etc/elasticsearch/elasticsearch.yml
        sed -i 's/^#LimitMEMLOCK/LimitMEMLOCK/g' /usr/lib/systemd/system/elasticsearch.service
        sed -i 's/^#MAX_LOCKED_MEMORY/MAX_LOCKED_MEMORY/g' /etc/sysconfig/elasticsearch
	      systemctl daemon-reload
	      systemctl enable elasticsearch
	      systemctl start elasticsearch
        
        yum install -y kibana
        sed -i 's/^#server.port/server.port/g' /etc/kibana/kibana.yml
        sed -i 's/^#elasticsearch.url/elasticsearch.url/g' /etc/kibana/kibana.yml
        sed -i 's/localhost:9200/192.168.11.101:9200/g' /etc/kibana/kibana.yml
        sed -i 's/^#server.host.*/server.host: 192.168.11.101/g' /etc/kibana/kibana.yml
        systemctl enable kibana
        systemctl start kibana

        yum install logstash -y

        fi
  	  SHELL

      end
  end
end
