# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :ipa => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
  },
  :client => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.102',
},
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
             vb.customize ["modifyvm", :id, "--memory", "2048"]
          end

            box.vm.provision "shell", inline: <<-SHELL
              setenforce 0
              mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
              hostnamectl set-hostname $HOSTNAME.otustest.local
              echo 192.168.11.101 ipa.otustest.local ipa>>/etc/hosts
              echo 192.168.11.102 client.otustest.local ipa>>/etc/hosts
              if [ "$HOSTNAME" = ipa ]
              then
              yum -y install ipa-server ipa-server-dns bind bind-dyndb-ldap
              systemctl start named
              systemctl enable named
              ipa-server-install -a secret12 --hostname=ipa.otustest.local -r OTUSTEST.LOCAL -p secret12 -n otustest.local -U
              fi
              if [ "$HOSTNAME" = client ]
              then
              yum install freeipa-client -y
              # this is not interactive. still need to run manually.
              #ipa-client-install --mkhomedir --principal=admin --domain=otustest.local --server=ipa.otustest.local --realm=OTUSTEST.LOCAL
              fi
  	  SHELL
      end
  end
end
