# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 500,
			:port => 1
		},
		:sata2 => {
                        :dfile => './sata2.vdi',
                        :size => 500,
			:port => 2
		},
                :sata3 => {
                        :dfile => './sata3.vdi',
                        :size => 500,
                        :port => 3
                },
                :sata4 => {
                        :dfile => './sata4.vdi',
                        :size => 500,
                        :port => 4
                },
                :sata5 => {
                        :dfile => './sata5.vdi',
                        :size => 500,
                        :port => 5
                }
	}

		
  },
}

Vagrant.configure("2") do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
	      # selinux off or moving home will ruin sshkey login
              setenforce 0
              mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
              for i in b c d e f; do pvcreate /dev/sd$i; done
              vgextend VolGroup00 /dev/sdb
              lvextend -l +100%FREE /dev/mapper/VolGroup00-LogVol00
              # check size of / befoure resize
              df /
              # extend ROOT
              xfs_growfs /dev/mapper/VolGroup00-LogVol00  
              #check size of / after resize
              df /
              # create VAR with mirror
              vgcreate VolGroup01 /dev/sdc /dev/sde
              lvcreate -l +100%FREE  -m1 -n LogVol_var VolGroup01
              mkfs.xfs /dev/mapper/VolGroup01-LogVol_var
              # create HOME
              vgcreate VolGroup02 /dev/sdf
              lvcreate -l 50%FREE -n LogVol_home VolGroup02
              mkfs.xfs /dev/mapper/VolGroup02-LogVol_home
              # move data, edit fstab, remount
              mkdir /home_new
              mount /dev/mapper/VolGroup02-LogVol_home /home_new
              rsync -av /home/* /home_new/
              rm -rf /home/*
              umount /home_new
              echo '/dev/mapper/VolGroup02-LogVol_home /home xfs defaults 0 0' >>/etc/fstab
              mount -a
              touch /home/vagrant/foo.bar
              ls /home/vagrant/foo.bar
              #create snapshot
              lvcreate -l 50%FREE -s -n LogVol_home_snap0 /dev/mapper/VolGroup02-LogVol_home
              # delete files
              rm /home/vagrant/foo.bar
              ls /home/vagrant/foo.bar
              # rollback
              umount /home 
              lvconvert --merge VolGroup02/LogVol_home_snap0
              mount -a
              # check again
              ls /home/vagrant/foo.bar
  	  SHELL

      end
  end
end