# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :server => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
  },
  :client => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.102',
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
                  vb.customize ["modifyvm", :id, "--memory", "1024"]
          end
 	  box.vm.provision "shell", inline: <<-SHELL
              setenforce 0
              mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
        yum install epel-release -y
               
        if [ "$HOSTNAME" = server ]
        then yum install bacula-directory bacula-console bacula-storage -y
        fi
        
        if [ "$HOSTNAME" = client ]
	      then
	      yum bacula-client -y
        fi
  	  SHELL

      end
  end
end
